services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spartan_outreach
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_NAME: spartan_outreach
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: